title: Welcome to my blog
author: lazysong
email: 1937941685@qq.com
description: > # this means to ignore newlines until "baseurl:"
 What is essential is invisible to the eye. It is only with the heart that you can see clearly.

# social links
twitter_username: your-twitter-handle
github_username:  lazysong

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
